# Generated by Django 4.2.23 on 2025-08-29 14:23

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=250,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator],
            ),
        ),
    ]
