# Generated by Django 4.2.23 on 2025-09-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendinguser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
